env:
  browser: true
  es2021: true
  jest: true
extends:
  - htmlacademy/react
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: '18'
